---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myapp-route
  namespace: default
spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: Host(`myapp.apps.caspersbox.com`)
      kind: Rule
      priority: 10
      services:
        - name: myapp-service
          port: 80
          weight: 100
          passHostHeader: true

  # TLS configuration (optional for HTTPS)
  # tls:
  #   secretName: app-example-com-tls