# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    argv:
      - "{{ global_dotfiles_path }}/bin/setup"
      - "-n {{ install_dotfiles_dotfiles_path }}/dotfiles.setup"
  changed_when: true
  register: install_dotfiles_deploy_out
