# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
#         NOTES:  This file was created specifically as a template
# ============================================================================
---
hostlist:
  hosts:
    fedora-local.local.caspersbox.com:
