#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  history
#         USAGE:  . history
#   DESCRIPTION:  Configures shell command history handling
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

history -a;
history -n;

declare -x HISTFILE="${HOME}/.bash_history";
declare -ix HISTSIZE=10000;
declare -ix HISTFILESIZE=10000;
declare -x HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S ";
declare -x HISTCONTROL="ignoredups:ignorespace";
declare -x HISTIGNORE="ls:ll:lt:la:l:cd:pwd:exit:mc:su:df:clear:cls:bg:fg";
