#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  defaults
#         USAGE:  . defaults
#   DESCRIPTION:  Sets default commandline options and variables for various programs
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

declare -x LESS_TERMCAP_mb=$'\e[1;32m';
declare -x LESS_TERMCAP_md=$'\e[1;32m';
declare -x LESS_TERMCAP_me=$'\e[0m';
declare -x LESS_TERMCAP_se=$'\e[0m';
declare -x LESS_TERMCAP_so=$'\e[01;33m';
declare -x LESS_TERMCAP_ue=$'\e[0m';
declare -x LESS_TERMCAP_us=$'\e[1;4;31m';
