# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Checkout setup from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles-setup.git
    dest: "{{ installer_path }}"
    version: main

- name: Checkout dotfiles from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles.git
    dest: "{{ checkout_path }}"
    version: main
