# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Checkout dotfiles from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles.git
    dest: "{{ common_checkout_path }}"
    version: main
