# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Make /var/tmp/ansible-installer/bin/setup executable
  ansible.builtin.file:
    path: "{{ installer_path }}/bin/setup"
    owner: "{{ remote_username }}"
    mode: '0755'
