# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Find and delete all symbolic links
  ansible.builtin.find:
    paths: "{{ ansible_facts.ansible_user_home }}"
    recurse: no
    follow: no
    type: "l"
  register: symlinks

- name: Delete found symlinks
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ symlinks.files }}"

- name: Remove existing dotfiles directory
  ansible.builtin.file:
    path: "{{ ansible_facts.ansible_user_home }}/.dotfiles"
    state: absent
