# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    cmd: "{{ global_installer_path | default('/var/tmp/checkout-setup') }}/bin/setup -n {{ global_checkout_path | default('/var/tmp/checkout-dotfiles') }}/config/dotfiles/dotfiles.setup"
  changed_when: true
  register: deploy_out
