# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    cmd: "/var/tmp/ansible-installer/bin/setup -n /var/tmp/dotfiles/config/dotfiles/dotfiles.setup"
  changed_when: true
  register: deploy_out
