# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    argv:
      - "{{ global_installer_path }}/bin/setup"
      - "-n {{ global_installer_path }}/dotfiles.setup"
  changed_when: true
  register: deploy_out
