# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    cmd: "{{ common_installer_path }}/bin/setup -n {{ common_checkout_path }}/config/dotfiles/dotfiles.setup"
  changed_when: true
  register: deploy_out
