# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Checkout setup from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles-setup.git
    dest: "{{ global_installer_path | default('/var/tmp/checkout-dotfiles') }}"
    version: main
