# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Pre-checkout cleanup - global installer path
  ansible.builtin.file:
    path: "{{ global_installer_path }}"
    state: absent

- name: Create temporary directories
  ansible.builtin.file:
    path: "{{ global_installer_path }}"
    state: directory
    mode: "0700"
        
- name: Checkout setup from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles-setup.git
    dest: "{{ global_installer_path }}"
    version: main
