# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Make setup executable
  ansible.builtin.file:
    path: "{{ global_installer_path }}/bin/setup"
    owner: "{{ ansible_facts['ansible_user_name'] }}"
    mode: '0755'
