# ====  ANSIBLE   =============================================================
#          NAME:  roles/common/tasks/create-tempdir.yml
#   DESCRIPTION:  Creates a temporary directory for use throughout the role
# =============================================================================
---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: role
  register: role_tempdir
