# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Deploy and install dotfiles

  pre_tasks:
    - name: Pre-installation cleanup
      ansible.builtin.file:
        path: /var/tmp/ansible-installer
        state: absent
    - name: Create temporary directory for code checkout
      ansible.builtin.file:
        path: /var/tmp/ansible-installer
        state: directory
        mode: '0700'
        owner: khuntly
        group: users

  hosts: dotfiles
  become: true
  become_user: khuntly
  roles:
    - common
    - install_dotfiles

  post_tasks:
    - name: Post-installation cleanup
      ansible.builtin.file:
        path: /var/tmp/ansible-installer
        state: absent
