# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Deploy and install dotfiles

  pre_tasks:
    - name: Create temporary directory for code checkout
      ansible.builtin.tempfile:
        state: directory
        suffix: role
      register: role_tempdir

  hosts: dotfiles
  become: true
  become_user: khuntly
  roles:
    - common
    - install_dotfiles

  post_tasks:
    - name: Post-installation cleanup
      ansible.builtin.file:
        path: "{{ role_tempdir.path }}"
        state: absent
