services:
  tomcat:
    build: ./tomcat
    image: tomcat:jre21
    container_name: tomcat-appserver
    restart: unless-stopped
    depends_on: tomcat-mysql

    environment:
      CATALINA_HOME: /opt/apache/tomcat/server
      CATALINA_BASE: /opt/apache/tomcat/instance
      CATALINA_LOG_ROOT: /opt/apache/tomcat/instance/logs
      CLASSPATH: /opt/apache/tomcat/instance/lib/mysql.jar
      JAVA_OPTS: >
        -Xms4096m -Xmx4096m -Xmn3072m -Djava.io.tmpdir=/var/tmp -XX:MaxDirectMemorySize=3072M -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m \
        -XX:+PrintGCDetails -XX:+UseParallelGC -verbose:gc -Xlog:gc=info:file=${CATALINA_LOG_ROOT}/gc.%t.log:pid,time,uptime -XX:+PrintGCDetails \
        -Dsun.reflect.inflationThreshold=0 -Djava.security.egd=file:/dev/./urandom -Dcom.sun.jndi.ldap.connect.pool.maxsize=200 -Dcom.ibm.cacheLocalHost=true \
        -Dcom.sun.jndi.ldap.connect.pool.prefsize=200 -Dcom.sun.jndi.ldap.connect.pool.timeout=3000 -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=600 -Djava.awt.headless=true \
        -Dcom.ibm.xml.xlxp.jaxb.opti.level=3 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${CATALINA_LOG_ROOT}/heapdump.%Y%m%d.%H%M%S.%pid.txt -Dfile.encoding=UTF-8 \
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.config.file=${CATALINA_BASE}/conf/jmxremote.properties

    ports:
      - "8443:8443/tcp"

    networks:
      tomcat:
        ipv4_address: 172.24.199.200

    volumes:
      - tomcat:/opt/apache/tomcat/instance

  mysql:
    build: ./mysql
    image: mysql:latest
    container_name: tomcat-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esolutions
      MYSQL_USER: appadm
      MYSQL_PASSWORD: apppass

    ports:
      - "3306:3306"

    networks:
      mysql:
        ipv4_address: 172.24.199.201

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  tomcat:
    driver: local
  mysql:
    driver: local

networks:
  tomcat:
    driver: bridge

    ipam:
      config:
        - subnet: 172.24.199.0/20
          gateway: 172.24.192.1

  mysql:
    driver: bridge

    ipam:
      config:
        - subnet: 172.24.199.0/20
          gateway: 172.24.192.1
