# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Kick off dotfiles install
  tasks:
    ansible.builtin.include_tasks:
      file: {{ item }}
  loop:
    - checkout-files.yml
    - deploy-files.yml
    - install-files.yml
  notify:
    - post-cleanup
