-- open the pluggable db
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN READ WRITE;
ALTER SESSION SET CONTAINER = FREEPDB1;

-- create tablespaces
CREATE TABLESPACE TS_DATA
DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/ts_data.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 50M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_IDX
DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/ts_idx.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 50M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

--
COMMIT;

EXIT;
