-- open the pluggable db
ALTER PLUGGABLE DATABASE ORCLPDB1 OPEN READ WRITE;
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- create tablespaces
CREATE TABLESPACE TS_DATA
DATAFILE '/opt/oracle/oradata/ORCLCDB/ts_data.dbf'
SIZE 10G
AUTOEXTEND ON NEXT 5G
MAXSIZE 50G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_IDX
DATAFILE '/opt/oracle/oradata/ORCLCDB/ts_idx.dbf'
SIZE 10G
AUTOEXTEND ON NEXT 5G
MAXSIZE 50G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

--
COMMIT;

EXIT;
