---
ALTER PLUGGABLE DATABASE ORCLPDB1 OPEN READ WRITE;
ALTER SESSION SET CONTAINER = ORCLPDB1;

---
CREATE TABLESPACE TS_DATA
DATAFILE '/opt/oracle/oradata/ORCLDB1/ts_data.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 50M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_IDX
DATAFILE '/opt/oracle/oradata/ORCLDB1/ts_idx.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 50M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

---
CREATE USER FIRCOCTY IDENTIFIED BY FIRCOCTY;
GRANT CONNECT TO FIRCOCTY;
GRANT CREATE SESSION TO FIRCOCTY;
GRANT ALL PRIVILEGES TO FIRCOCTY;

---
CREATE USER FIRCOLS IDENTIFIED BY FIRCOLS;
GRANT CONNECT TO FIRCOLS;
GRANT CREATE SESSION TO FIRCOLS;
GRANT ALL PRIVILEGES TO FIRCOLS;

---
COMMIT;
