#=====  ANSIBLE   =============================================================
#          NAME:  roles/common/handlers/post-cleanup.yml
#   DESCRIPTION:  Main entry point for common tasks
#==============================================================================
---
