#======  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
#==============================================================================
---

- name: Deploy installation files
  ansible.builtin.command:
    argv:
      - {{ role_tempdir }}/bin/setup
      - -n dotfiles
      - -a deployFiles
  register: deploy_out