# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Kick off dotfiles install
  tasks:
    include_tasks:
      - tasks/checkout-files
      - tasks/deploy-files
      - tasks/install-files
    notify:
      - handlers/post-cleanup
