# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Kick off dotfiles install
  tasks:
    include_tasks:
      - checkout-files
      - deploy-files
      - install-files
    notify:
      - post-cleanup
