# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Deploy and install dotfiles

  pre_tasks:
    - name: Pre-installation cleanup
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ checkout_path }}"
        - ansible-installer

    - name: Create temporary directory for setup checkout
      ansible.builtin.file:
        path: "{{ installer_path }}"
        state: directory
        mode: '0700'
    - name: Create temporary directory for dotfiles checkout
      ansible.builtin.file:
        path: "{{ checkout_path }}"
        state: directory
        mode: '0700'

  hosts: dotfiles
  become: true
  become_user: "{{ remote_username }}"
  roles:
    - common
    - install_dotfiles

  post_tasks:
    - name: Post-installation cleanup
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ checkout_path }}"
        - ansible-installer
