# ====  ANSIBLE   =============================================================
#          NAME:  meta/main.yml
#   DESCRIPTION:  Meta information for this playbook
# =============================================================================
---
addhosts:
  hosts:
    addhost.host.com:
