#======  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
#=============================================================================
---
- name: Deploy and install dotfiles
  hosts: all
  roles:
    - common
    - install-dotfiles
