# =====  ANSIBLE  ============================================================
#          NAME:  tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Checkout dotfiles from Github
  ansible.builtin.git:
    repo: https://github.com/cws-khuntly/dotfiles.git
    dest: "{{ role_tempdir }}"
    version: main
