# ====  ANSIBLE   =============================================================
#          NAME:  roles/common/tasks/main.yml
#   DESCRIPTION:  Main entry point for common tasks
# =============================================================================
---
- name: Main entry point for files install
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - checkout-files.yml
    - deploy-files.yml
    - install-files.yml
