# ====  ANSIBLE   =============================================================
#          NAME:  roles/common/tasks/main.yml
#   DESCRIPTION:  Main entry point for common tasks
# =============================================================================
---
- name: Main entry point for dotfiles install
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - checkout-dotfiles.yml
    - deploy-files.yml
    - install-files.yml

- name: Send notifications
  notify:
    - post-install-cleanup
