# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    cmd: "{{ role_tempdir.path }}/bin/setup -n dotfiles"
  changed_when: false
  register: deploy_out
