# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Deploy installation files
  ansible.builtin.command:
    cmd: /opt/tmp/ansible-installer/bin/setup -n dotfiles"
  changed_when: true
  register: deploy_out
