#===  CONFIGURATION  ==========================================================
#          NAME:  E09-network
#   DESCRIPTION:  Configuration file defining directories and platforms
#    PARAMETERS:  N/A
#       RETURNS:  N/A
#==============================================================================

_TRUE="true";
_FALSE="false";

#==============================================================================
# enable various items for logging. usually used in debugging during
# development, but can be used for edge cases in a production setting.
#
# LOG_ROOT: Full path to the directory logs are written to. Variables can be used.
#          This is a global and per-plugin variable. If a plugin desires to
#          override, it can.
# ARCHIVE_LOG_ROOT: The directory archive logs are written to, relative to log_root
#          This is a global and per-plugin variable. If a plugin desires to
#          override, it can.
#==============================================================================
LOG_ROOT="${HOME}/log";

#==============================================================================
# enable various items for logging. usually used in debugging during
# development, but can be used for edge cases in a production setting.
#
#    ENABLE_DEBUG: true/false - if debug is on a lot of messages about runtime
#                  will get printed to the debug log
#    ENABLE_TRACE: true/false - turns on shell debug (set -vx)
#==============================================================================
ENABLE_DEBUG="${_TRUE}";
ENABLE_VERBOSE="${_TRUE}";
ENABLE_TRACE="${_FALSE}";
ENABLE_PERFORMANCE="${_FALSE}";

#==============================================================================
# enable/disable logging verbosity for the actual logger. don't use this
# unless you *really* need to.
#
#    ENABLE_LOGGER_VERBOSE: true/false - if debug is on a lot of messages about runtime
#                  will get printed to the debug log
#    ENABLE_LOGGER_TRACE: true/false - turns on shell debug (set -vx)
#==============================================================================
ENABLE_LOGGER_VERBOSE="${_FALSE}";
ENABLE_LOGGER_TRACE="${_FALSE}";

#==============================================================================
# conversion pattern. based off log4j. using log4j items in the conversion
#
# CONVERSION_PATTERN: How should we translate and present information ?
#   The conversion pattern goes like this:
#     [Time: %s] - The timestamp of the written message
#     [Thread: %s] - thread
#     [Log: %s] - log file
#     [Level: %s] - log level
#     [File: %s:%s] - source file:function
#     [Method: %s] - line number
#     %s - message
# TIMESTAMP_OPTS - The options provided to the date command when writing message entries
#==============================================================================
CONVERSION_PATTERN="[Time: %s] [Log: %s] [Level: %s] - [Thread: %d] [File: %s:%d] [Method: %s] - %s";
TIMESTAMP_OPTS="%d/%m/%Y %H:%M:%S";

#==============================================================================
# define the logfile names
#==============================================================================
PERF_LOG_FILE="performance.log";
ERROR_LOG_FILE="error.log";
DEBUG_LOG_FILE="debug.log";
AUDIT_LOG_FILE="audit.log";
WARN_LOG_FILE="warn.log";
INFO_LOG_FILE="info.log";
DEFAULT_LOG_FILE="default.log";

#==============================================================================
# complete - report as such
#==============================================================================
LOGGING_LOADED="${_TRUE}";
