# =====  WORKFLOW  ============================================================
#          NAME:  ansible-linter.yml
#   DESCRIPTION:  GitHub action for yaml linter
# ============================================================================
name: Create release package
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## New Release
            New release.
          draft: false
          prerelease: false
